### ISSUE TITLE
"there is no test for this task"

### ISSUE THREAD

**Issue by petraBT** [France-ioi/taskgrader#54]
We just moved and renamed a task, created a new LTI link and embedded this link in edX. It can no longer find its tests however:

![Screen Shot 2019-12-02 at 11 01 18 AM](https://user-images.githubusercontent.com/33522257/69974599-95241600-14f3-11ea-83b8-0165183ee868.png)

**Comment by mblockelet** [comment]
Hi, I can confirm the issue ; you might encounter it with other tasks as well until I fixed the issue, which I aim to do within an hour or two.

**Comment by mblockelet** [comment]
I fixed part of the issue, and this task is now working. I still have another part of the issue to fix.

**Comment by mblockelet** [comment]
I fixed the rest, by fixing some old data in your repository ; not sure why how this data got invalid in the first place, but it's fixed now. Please tell me if the issue happens again!

**Comment by petraBT** [comment]
It is working for the one task (gameOfErrors - now renamed - here it is: http://task-editor.france-ioi.org/#edit/cspace%2F01%20C%20Programming%20Getting%20Started%2FUnit%201.1%20Printing%20loops%2C%20and%20comments%2F03%20Correcting%20simple%20syntax%20errors%2F02_correct%20simple%20syntax%20errors) now but NOT for other tasks that I just moved (and I pulled all changes before working). Here is one that is not working: http://task-editor.france-ioi.org/#edit/cspace%2F01%20C%20Programming%20Getting%20Started%2FUnit%201.1%20Printing%20loops%2C%20and%20comments%2F04%20Printing%20text%20and%20new%20lines%2F02_print%20text%20over%20several%20lines

What is really odd is that when we look at the JSON file (even for the task that is working) it lists the names of the test files as gameOfErrors.in and gameOfErrors.out, but when we look at the folder containing the tests there are only test1.in and test1.out in there. Thanks!

**Comment by mblockelet** [comment]
Hi, sorry the issue is still there.

For the test files filenames, it's normal ; the file names are for you but internally they will be saved as testN.in / testN.out.

The issue here is a combination of two issues :

* a bug in a newer internal feature of task-editor, designed to cull useless data ; this bug shouldn't happen in a normal usage of the task-editor, but here it happens because of...
* invalid data in the older tasks, for which I have no idea how it appeared (it has been there for at least a few months), and which has been left fine until now with that internal feature of task-editor

The combination of both ends up with an invalid taskSettings.json file generated, which will sometimes lack a "compilationExecution" or "runExecution" keys at some points because they have been culled as useless invalid data, and then when it is evaluated by the taskgrader, the testing part is rejected as it's missing those required keys, and you get the "There is no test for this task" error.

I looked into the first issue yesterday but it will probably take a long time to fix, hence I tried fixing the invalid data (second issue) yesterday. However, I didn't take into account that some invalid data might already have been culled, and hence went undetected by my fixes. I just tried fixing that, and it works on the second task you linked here ; hopefully, this should be fine now. I tested on a few tasks and it seems to be fine but that might not be the case for all tasks.

Please tell me if you encounter the issue again.

**Comment by petraBT** [comment]
Thank you so much! I just ran a new test of moving / renaming a task and all went smoothly. We’ll now get our TAs going on moving lots of tasks, so if the error happens again we should know shortly. But for now it all looks good - thank you!!

—Petra

On Dec 3, 2019, at 12:37 PM, mblockelet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, sorry the issue is still there.

For the test files filenames, it's normal ; the file names are for you but internally they will be saved as testN.in / testN.out.

The issue here is a combination of two issues :

  *   a bug in a newer internal feature of task-editor, designed to cull useless data ; this bug shouldn't happen in a normal usage of the task-editor, but here it happens because of...
  *   invalid data in the older tasks, for which I have no idea how it appeared (it has been there for at least a few months), and which has been left fine until now with that internal feature of task-editor

The combination of both ends up with an invalid taskSettings.json file generated, which will sometimes lack a "compilationExecution" or "runExecution" keys at some points because they have been culled as useless invalid data, and then when it is evaluated by the taskgrader, the testing part is rejected as it's missing those required keys, and you get the "There is no test for this task" error.

I looked into the first issue yesterday but it will probably take a long time to fix, hence I tried fixing the invalid data (second issue) yesterday. However, I didn't take into account that some invalid data might already have been culled, and hence went undetected by my fixes. I just tried fixing that, and it works on the second task you linked here ; hopefully, this should be fine now. I tested on a few tasks and it seems to be fine but that might not be the case for all tasks.

Please tell me if you encounter the issue again.

**Comment by mblockelet** [comment]
We just fixed the other issue with task-editor, it ended up being a bit faster than I thought. Hopefully now this specific issue shouldn't arise again, so if it says "there is no test for this task", it will probably be another issue.
